USE magazzino;

-- etichette
TRUNCATE TABLE etichette;

-- proprieta tags sel 1
CALL input_proprieta('1','ATTREZZI');
CALL input_proprieta('1','BRETELLA');
CALL input_proprieta('1','APPARATI');
CALL input_proprieta('1','COMPONENTI');
CALL input_proprieta('1','Minuteria');
CALL input_proprieta('1','Pannelli');
CALL input_proprieta('1','SERVER');
CALL input_proprieta('1','VARI');
CALL input_proprieta('1','Viteria');
CALL input_proprieta('1','ADAPTER');
CALL input_proprieta('1','BLADE');
CALL input_proprieta('1','CHASSIS');
CALL input_proprieta('1','CHECKPOINT');
CALL input_proprieta('1','DISCHI');
CALL input_proprieta('1','DISTRIBUTIONPOWER');
CALL input_proprieta('1','DVDRW');
CALL input_proprieta('1','FIREWALL');
CALL input_proprieta('1','FO-LC-LC-50/125');
CALL input_proprieta('1','FO-LC-LC-9/125');
CALL input_proprieta('1','FO-LC-SC-50/125');
CALL input_proprieta('1','FO-LC-SC-9/125');
CALL input_proprieta('1','FO-SC-SC-50/125');
CALL input_proprieta('1','HPDL360');
CALL input_proprieta('1','HPDL380PGEN8');
CALL input_proprieta('1','KVM');
CALL input_proprieta('1','LICENZASOFTWARE');
CALL input_proprieta('1','MONITOR');
CALL input_proprieta('1','Plastica');
CALL input_proprieta('1','SPINE');
CALL input_proprieta('1','STORAGE');
CALL input_proprieta('1','SWITCH');
CALL input_proprieta('1','UTP');
CALL input_proprieta('1','CAT5E');
CALL input_proprieta('1','CAT6');
CALL input_proprieta('1','Vitiedadigabbia');
CALL input_proprieta('1','10M');
CALL input_proprieta('1','10UR');
CALL input_proprieta('1','12,5M');
CALL input_proprieta('1','12M');
CALL input_proprieta('1','15M');
CALL input_proprieta('1','17inch');
CALL input_proprieta('1','1UR');
CALL input_proprieta('1','20M');
CALL input_proprieta('1','25M');
CALL input_proprieta('1','26M');
CALL input_proprieta('1','27M');
CALL input_proprieta('1','2M');
CALL input_proprieta('1','2UR');
CALL input_proprieta('1','30M');
CALL input_proprieta('1','35M');
CALL input_proprieta('1','3M');
CALL input_proprieta('1','3UR');
CALL input_proprieta('1','50M');
CALL input_proprieta('1','5M');
CALL input_proprieta('1','5UR');
CALL input_proprieta('1','65inch');
CALL input_proprieta('1','8TB');
CALL input_proprieta('1','Pacchi');
CALL input_proprieta('1','Scatola');
CALL input_proprieta('1','USB');
CALL input_proprieta('1','VGA');
CALL input_proprieta('1','3m-Kabel');
CALL input_proprieta('1','48-PORT');
CALL input_proprieta('1','ADATTATORE');
CALL input_proprieta('1','CAVI');
CALL input_proprieta('1','RAME');
CALL input_proprieta('1','FIBRA');
CALL input_proprieta('1','blu');
CALL input_proprieta('1','CENTRASTAR');
CALL input_proprieta('1','CISCO');
CALL input_proprieta('1','NEXSUS');
CALL input_proprieta('1','COLOUR');
CALL input_proprieta('1','CODING');
CALL input_proprieta('1','PATCH');
CALL input_proprieta('1','C6');
CALL input_proprieta('1','BLUE');
CALL input_proprieta('1','GIALLO');
CALL input_proprieta('1','EMC');
CALL input_proprieta('1','ATMOS');
CALL input_proprieta('1','POSTEL');
CALL input_proprieta('1','ENCLOSURE');
CALL input_proprieta('1','LCD');
CALL input_proprieta('1','FUJITSU');
CALL input_proprieta('1','RX600');
CALL input_proprieta('1','giallo');
CALL input_proprieta('1','HP');
CALL input_proprieta('1','FLASH');
CALL input_proprieta('1','IBM');
CALL input_proprieta('1','3850-X5');
CALL input_proprieta('1','DS8800');
CALL input_proprieta('1','50.4TB');
CALL input_proprieta('1','57.6TB');
CALL input_proprieta('1','SAN');
CALL input_proprieta('1','48');
CALL input_proprieta('1','LED');
CALL input_proprieta('1','MD65C');
CALL input_proprieta('1','ORACLE');
CALL input_proprieta('1','SL8500');
CALL input_proprieta('1','TAPE');
CALL input_proprieta('1','CLEARING');
CALL input_proprieta('1','PASSACAVI');
CALL input_proprieta('1','Plexiglass');
CALL input_proprieta('1','PLUGIN');
CALL input_proprieta('1','MODULE');
CALL input_proprieta('1','CPU');
CALL input_proprieta('1','AMD');
CALL input_proprieta('1','POSTEL');
CALL input_proprieta('1','POSTEMOBILE');
CALL input_proprieta('1','CERT');
CALL input_proprieta('1','ASA');
CALL input_proprieta('1','GATEWAY');
CALL input_proprieta('1','SCHEDE');
CALL input_proprieta('1','ptnumber');
CALL input_proprieta('1','RX600');
CALL input_proprieta('1','RACK');
CALL input_proprieta('1','TFT');
CALL input_proprieta('1','RC25');
CALL input_proprieta('1','43cm');
CALL input_proprieta('1','RMA');
CALL input_proprieta('1','S4-0812');
CALL input_proprieta('1','digital');
CALL input_proprieta('1','vm_1he');
CALL input_proprieta('1','SL8500');
CALL input_proprieta('1','TELEFONO');
CALL input_proprieta('1','VOIP');
CALL input_proprieta('1','VBLOCK');
CALL input_proprieta('1','VMAX');
CALL input_proprieta('1','STORAGE');

-- etichette posizioni sel 2
CALL input_proprieta('2','A1L02');
CALL input_proprieta('2','A1L05');
CALL input_proprieta('2','A1L11');
CALL input_proprieta('2','A1L12');
CALL input_proprieta('2','A1L13');
CALL input_proprieta('2','A2L01');
CALL input_proprieta('2','A2L02');
CALL input_proprieta('2','A2L03');
CALL input_proprieta('2','A2L04');
CALL input_proprieta('2','A2L05');
CALL input_proprieta('2','A2L09');
CALL input_proprieta('2','A2L10');
CALL input_proprieta('2','A2L13');
CALL input_proprieta('2','A2L14');
CALL input_proprieta('2','B1L02');
CALL input_proprieta('2','B1L03');
CALL input_proprieta('2','B1L04');
CALL input_proprieta('2','B1L11');
CALL input_proprieta('2','B1L13');
CALL input_proprieta('2','B2-L4');
CALL input_proprieta('2','B2-L5');
CALL input_proprieta('2','P01');
CALL input_proprieta('2','P05');
CALL input_proprieta('2','P06');
CALL input_proprieta('2','P10');
CALL input_proprieta('2','P17');
CALL input_proprieta('2','Z1L08');

-- etichette destinazioni sel 3
CALL input_proprieta('3','SALA1');
CALL input_proprieta('3','temp');
CALL input_proprieta('3','UFFICIO1');
CALL input_proprieta('3','SALA1-ISOLA5');
CALL input_proprieta('3','SALA1-ISOLA6');
CALL input_proprieta('3','SALA1-ISOLASTORAGE');
CALL input_proprieta('3','SALA1ISOLA2');
CALL input_proprieta('3','SALA2');
CALL input_proprieta('3','TLCA');
CALL input_proprieta('3','TLCB');
CALL input_proprieta('3','UFFICI');
CALL input_proprieta('3','INGRESSO');

-- etichette tipi di documenti sel 4
CALL input_proprieta('4','BDC');
CALL input_proprieta('4','DDT');
CALL input_proprieta('4','eMail');
CALL input_proprieta('4','Lettera_di_vettura');
CALL input_proprieta('4','MDS');
CALL input_proprieta('4','ODA');
CALL input_proprieta('4','Verbale_di_consegna_ed_installazione');
CALL input_proprieta('4','CarrierB');

-- etichette registro sel 5
CALL input_proprieta('5','BRT SPA');
CALL input_proprieta('5','CAMI SOLUTION');
CALL input_proprieta('5','Carugati Luigi S.r.l.');
CALL input_proprieta('5','CEVA LOGISTIC ITALIA SRL');
CALL input_proprieta('5','Computer Gross Italia S.p.A.');
CALL input_proprieta('5','Converge S.p.A.');
CALL input_proprieta('5','D&T Delli TecnoTrans S.r.l.');
CALL input_proprieta('5','DGS S.p.A.');
CALL input_proprieta('5','DHL Express');
CALL input_proprieta('5','EMC Computer Systems Italia S.p.a.');
CALL input_proprieta('5','Ericsson Telecomunicazioni S.p.A');
CALL input_proprieta('5','EXECUTIVE');
CALL input_proprieta('5','Fimm S.R.L.');
CALL input_proprieta('5','Fujitsu Technology Solutions S.r.l.');
CALL input_proprieta('5','G.F.O. Europe S.r.l.');
CALL input_proprieta('5','Gebrueder Weiss GmbH Transport und Logistik');
CALL input_proprieta('5','Hewlett Packard International Sarl');
CALL input_proprieta('5','Hewlett Packard Italiana S.p.A.');
CALL input_proprieta('5','HMS IT S.p.A.');
CALL input_proprieta('5','ICT Logistica S.p.A.');
CALL input_proprieta('5','IRCE SPA');
CALL input_proprieta('5','Italia Logistica S.R.L.');
CALL input_proprieta('5','Italtel S.p.A.');
CALL input_proprieta('5','Laziale Distribuzione');
CALL input_proprieta('5','LUPPRIANS');
CALL input_proprieta('5','Mauden S.p.a.');
CALL input_proprieta('5','MITSafetrans S.r.l.');
CALL input_proprieta('5','NBI S.R.L.');
CALL input_proprieta('5','Nouwens Transport Breda');
CALL input_proprieta('5','Oracle Corporation');
CALL input_proprieta('5','Polo Immobiliare');
CALL input_proprieta('5','Polycom');
CALL input_proprieta('5','Poste Italiane S.p.a.');
CALL input_proprieta('5','Poste Italiane S.p.a. Immobiliare');
CALL input_proprieta('5','Poste Italiane S.p.a. ROMA');
CALL input_proprieta('5','PosteMobile S.p.a.');
CALL input_proprieta('5','R&M');
CALL input_proprieta('5','Rhenus Logistics');
CALL input_proprieta('5','RTI INFORDATA S.p.a.');
CALL input_proprieta('5','Safe Watcher S.r.l.');
CALL input_proprieta('5','SDA Express Courier');
CALL input_proprieta('5','Sioli & Fontana S.r.l.');
CALL input_proprieta('5','Tecnotrans S.r.l.');
CALL input_proprieta('5','Telecom Italia');
CALL input_proprieta('5','TRADIS di Giuseppe Pullella');

-- REGISTRO
TRUNCATE TABLE REGISTRO;
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('196', 'CAMI SOLUTION', 'DDT','56 DEL 13/02/2014', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('57','Computer Gross Italia S.p.A.','DDT','7089/ZD', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('29','Computer Gross Italia S.p.A.','DDT','95.349',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('27','Converge S.p.A.', 'DDT','ESP013033', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('34','DGS S.p.A.','DDT','81/13 A', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('23','EMC Computer Systems Italia S.p.a.','DDT','808', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('24','EMC Computer Systems Italia S.p.a.','DDT','809', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('30','EMC Computer Systems Italia S.p.a.','DDT','985', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('128', 'Ericsson Telecomunicazioni S.p.A','DDT','50165722',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('127', 'Ericsson Telecomunicazioni S.p.A','DDT','50165763',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('199', 'Ericsson Telecomunicazioni S.p.A','MDS','101', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('43','Fimm S.R.L.', 'DDT','8', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('41','Fujitsu Technology Solutions S.r.l.', 'DDT','189003648', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('62','Fujitsu Technology Solutions S.r.l.', 'DDT','189205293', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('11','Fujitsu Technology Solutions S.r.l.', 'DDT','189340594', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('3', 'Fujitsu Technology Solutions S.r.l.', 'DDT','189340596', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('5', 'Fujitsu Technology Solutions S.r.l.', 'DDT','189340597', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('9', 'Fujitsu Technology Solutions S.r.l.', 'DDT','189349594', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('8', 'Fujitsu Technology Solutions S.r.l.', 'DDT','189367488', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('6', 'Fujitsu Technology Solutions S.r.l.', 'DDT','189367489', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('49','G.F.O. Europe S.r.l.','DDT','11',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('194', 'Hewlett Packard International Sarl','BDC','GWOF 205389/050/01 C',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('190', 'Hewlett Packard International Sarl','BDC','GWOF 205478/041/01 C',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('192', 'Hewlett Packard International Sarl','BDC','GWOF 205478/047/01 C',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('17','Hewlett Packard International Sarl','DDT','GW0F 192498/099/01 C',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('19','Hewlett Packard International Sarl','DDT','GW0F 192650/050/01 C',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('20','Hewlett Packard International Sarl','DDT','GW0F 192779/057/01 C',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('18','Hewlett Packard International Sarl','DDT','GW0F 193223/001/01 C',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('21','Hewlett Packard International Sarl','DDT','GW0F 194285/014/01 C',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('15','Hewlett Packard International Sarl','DDT','GW0F 202277/032/01 C',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('1', 'HMS IT S.p.A.', 'DDT','R/55',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('195', 'IRCE SPA','Lettera_di_vettura', '171000026829 3/2/2014', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('38','Italtel S.p.A.','DDT','NVLS 60071134', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('40','Italtel S.p.A.','DDT','NVLS 60071135', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('31','Italtel S.p.A.','DDT','NVLS 60072390', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('33','Italtel S.p.A.','DDT','NVLS 60073100', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('32','Italtel S.p.A.','DDT','NVLS 60073110', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('204', 'Italtel S.p.A.','DDT','NVLS 60074311', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('139', 'LUPPRIANS', 'Lettera_di_vettura', 'P1028767VB001851 CSC',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('183', 'Mauden S.p.a.', 'DDT','11',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('66','Mauden S.p.a.', 'DDT','339', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('64','Mauden S.p.a.', 'DDT','340', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('46','Mauden S.p.a.', 'DDT','8', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('44','Mauden S.p.a.', 'Lettera_di_vettura', '13 - 000103', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('47','Mauden S.p.a.', 'Verbale_di_consegna_ed_installazione', 'mauden del 25-01-2013', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('26','Oracle Corporation','DDT','31840741',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('22','Oracle Corporation','DDT','6754892', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('202', 'Polo Immobiliare','eMail','22/05/2014',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('203', 'Polo Immobiliare','eMail','del 22/05/2014',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('201', 'Polo Immobiliare','eMail','del 22/06/2014',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('14','Polycom', 'DDT','14461', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('189', 'Poste Italiane S.p.a.', 'MDS','100', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('89','Poste Italiane S.p.a.', 'MDS','11',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('92','Poste Italiane S.p.a.', 'MDS','14',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('94','Poste Italiane S.p.a.', 'MDS','16',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('95','Poste Italiane S.p.a.', 'MDS','17',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('96','Poste Italiane S.p.a.', 'MDS','18',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('97','Poste Italiane S.p.a.', 'MDS','19',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('98','Poste Italiane S.p.a.', 'MDS','20',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('99','Poste Italiane S.p.a.', 'MDS','21',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('101', 'Poste Italiane S.p.a.', 'MDS','23',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('102', 'Poste Italiane S.p.a.', 'MDS','24',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('104', 'Poste Italiane S.p.a.', 'MDS','26',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('105', 'Poste Italiane S.p.a.', 'MDS','27',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('107', 'Poste Italiane S.p.a.', 'MDS','29',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('112', 'Poste Italiane S.p.a.', 'MDS','30',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('115', 'Poste Italiane S.p.a.', 'MDS','33',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('117', 'Poste Italiane S.p.a.', 'MDS','34',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('118', 'Poste Italiane S.p.a.', 'MDS','35',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('119', 'Poste Italiane S.p.a.', 'MDS','36',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('120', 'Poste Italiane S.p.a.', 'MDS','37',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('121', 'Poste Italiane S.p.a.', 'MDS','38',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('122', 'Poste Italiane S.p.a.', 'MDS','39',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('123', 'Poste Italiane S.p.a.', 'MDS','40',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('124', 'Poste Italiane S.p.a.', 'MDS','41',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('125', 'Poste Italiane S.p.a.', 'MDS','42',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('126', 'Poste Italiane S.p.a.', 'MDS','43',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('129', 'Poste Italiane S.p.a.', 'MDS','44',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('130', 'Poste Italiane S.p.a.', 'MDS','45',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('131', 'Poste Italiane S.p.a.', 'MDS','46',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('132', 'Poste Italiane S.p.a.', 'MDS','47',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('133', 'Poste Italiane S.p.a.', 'MDS','48',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('134', 'Poste Italiane S.p.a.', 'MDS','49',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('135', 'Poste Italiane S.p.a.', 'MDS','50',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('136', 'Poste Italiane S.p.a.', 'MDS','51',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('137', 'Poste Italiane S.p.a.', 'MDS','52',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('138', 'Poste Italiane S.p.a.', 'MDS','53',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('140', 'Poste Italiane S.p.a.', 'MDS','54',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('141', 'Poste Italiane S.p.a.', 'MDS','55',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('142', 'Poste Italiane S.p.a.', 'MDS','56',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('143', 'Poste Italiane S.p.a.', 'MDS','57',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('144', 'Poste Italiane S.p.a.', 'MDS','58',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('145', 'Poste Italiane S.p.a.', 'MDS','59',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('146', 'Poste Italiane S.p.a.', 'MDS','60',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('147', 'Poste Italiane S.p.a.', 'MDS','61',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('148', 'Poste Italiane S.p.a.', 'MDS','62',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('149', 'Poste Italiane S.p.a.', 'MDS','63',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('150', 'Poste Italiane S.p.a.', 'MDS','64',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('151', 'Poste Italiane S.p.a.', 'MDS','65',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('152', 'Poste Italiane S.p.a.', 'MDS','66',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('153', 'Poste Italiane S.p.a.', 'MDS','67',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('154', 'Poste Italiane S.p.a.', 'MDS','68',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('155', 'Poste Italiane S.p.a.', 'MDS','69',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('156', 'Poste Italiane S.p.a.', 'MDS','70',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('157', 'Poste Italiane S.p.a.', 'MDS','71',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('158', 'Poste Italiane S.p.a.', 'MDS','72',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('159', 'Poste Italiane S.p.a.', 'MDS','73',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('160', 'Poste Italiane S.p.a.', 'MDS','74',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('161', 'Poste Italiane S.p.a.', 'MDS','75',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('162', 'Poste Italiane S.p.a.', 'MDS','76',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('163', 'Poste Italiane S.p.a.', 'MDS','77',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('164', 'Poste Italiane S.p.a.', 'MDS','78',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('165', 'Poste Italiane S.p.a.', 'MDS','79',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('166', 'Poste Italiane S.p.a.', 'MDS','80',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('167', 'Poste Italiane S.p.a.', 'MDS','81',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('168', 'Poste Italiane S.p.a.', 'MDS','82',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('169', 'Poste Italiane S.p.a.', 'MDS','83',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('170', 'Poste Italiane S.p.a.', 'MDS','84',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('171', 'Poste Italiane S.p.a.', 'MDS','85',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('172', 'Poste Italiane S.p.a.', 'MDS','86',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('173', 'Poste Italiane S.p.a.', 'MDS','87',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('174', 'Poste Italiane S.p.a.', 'MDS','88',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('176', 'Poste Italiane S.p.a.', 'MDS','89',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('179', 'Poste Italiane S.p.a.', 'MDS','91',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('180', 'Poste Italiane S.p.a.', 'MDS','92',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('181', 'Poste Italiane S.p.a.', 'MDS','93',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('187', 'Poste Italiane S.p.a.', 'MDS','98',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('188', 'Poste Italiane S.p.a.', 'MDS','99',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('79','Poste Italiane S.p.a. Immobiliare', 'MDS','1', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('90','Poste Italiane S.p.a. Immobiliare', 'MDS','12',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('80','Poste Italiane S.p.a. Immobiliare', 'MDS','2', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('81','Poste Italiane S.p.a. Immobiliare', 'MDS','3', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('113', 'Poste Italiane S.p.a. Immobiliare', 'MDS','31',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('114', 'Poste Italiane S.p.a. Immobiliare', 'MDS','32',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('82','Poste Italiane S.p.a. Immobiliare', 'MDS','4', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('83','Poste Italiane S.p.a. Immobiliare', 'MDS','5', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('84','Poste Italiane S.p.a. Immobiliare', 'MDS','6', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('86','Poste Italiane S.p.a. Immobiliare', 'MDS','8', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('87','Poste Italiane S.p.a. Immobiliare', 'MDS','9', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('182', 'Poste Italiane S.p.a. Immobiliare', 'MDS','94',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('184', 'Poste Italiane S.p.a. Immobiliare', 'MDS','95',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('185', 'Poste Italiane S.p.a. Immobiliare', 'MDS','96',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('186', 'Poste Italiane S.p.a. Immobiliare', 'MDS','97',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('191', 'Poste Italiane S.p.a.','BDC','4509120039',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('193', 'Poste Italiane S.p.a.','BDC','4509131494',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('36','Poste Italiane S.p.a. ROMA','DDT','3', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('178', 'Poste Italiane S.p.a. ROMA','eMail','FORNITURA NERVI 7 OTTOBRE', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('175', 'Poste Italiane S.p.a. ROMA','eMail','mail di chirico del 10/03/2014',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('61','Poste Italiane S.p.a. ROMA','eMail','mail-pt#01',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('200', 'Poste Italiane S.p.a. ROMA','eMail','mail_cappadona_amedeo_5_7_2013',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('77','Poste Italiane S.p.a. ROMA','eMail','mainas salvatore del 22 gennaio', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('60','Poste Italiane S.p.a.','ODA','0422001369/1',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('111', 'Poste Italiane S.p.a.','ODA','4100016351',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('42','Poste Italiane S.p.a.','ODA','4100108870',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('45','Poste Italiane S.p.a.','ODA','4100110391',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('48','Poste Italiane S.p.a.','ODA','410011391', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('4', 'Poste Italiane S.p.a.','ODA','4100135698',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('13','Poste Italiane S.p.a.','ODA','4100137014',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('7', 'Poste Italiane S.p.a.','ODA','4100137674',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('2', 'Poste Italiane S.p.a.','ODA','4100138062',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('16','Poste Italiane S.p.a.','ODA','4100138063',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('35','Poste Italiane S.p.a.','ODA','422001710', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('39','Poste Italiane S.p.a.','ODA','4222001515',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('63','Poste Italiane S.p.a.','ODA','4501182411',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('65','Poste Italiane S.p.a.','ODA','4501182589',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('28','Poste Italiane S.p.a.','ODA','4501184977',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('10','Poste Italiane S.p.a.','ODA','4501186488',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('197', 'Poste Italiane S.p.a.','ODA','4509054989T', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('88','PosteMobile S.p.a.','MDS','10',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('198', 'PosteMobile S.p.a.','MDS','101', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('91','PosteMobile S.p.a.','MDS','13',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('93','PosteMobile S.p.a.','MDS','15',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('100', 'PosteMobile S.p.a.','MDS','22',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('103', 'PosteMobile S.p.a.','MDS','25',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('106', 'PosteMobile S.p.a.','MDS','28',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('85','PosteMobile S.p.a.','MDS','7', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('177', 'PosteMobile S.p.a.','MDS','90',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('50','R&M', 'DDT','296', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('52','R&M', 'DDT','428', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('58','R&M', 'DDT','438', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('53','R&M', 'DDT','465', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('54','R&M', 'DDT','467', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('55','R&M', 'DDT','518', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('56','R&M', 'DDT','544', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('12','RTI INFORDATA S.p.a.','DDT','080/RM',NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('51','RTI INFORDATA S.p.a.','DDT','1300756', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('59','SDA Express Courier', 'Lettera_di_vettura', '1214813101738', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('25','Telecom Italia','DDT','127', NULL, NULL, NULL);
INSERT INTO REGISTRO(id_registro, contatto, tipo, numero, gruppo, data, file) VALUES('37','Telecom Italia','DDT','169/RZ/2013', NULL, NULL, NULL);

-- MERCE
TRUNCATE TABLE MERCE;
INSERT INTO MERCE(id_merce, tags) VALUES('1', 'SERVER IBM 3850-X5 ridontati doppioseriale');
INSERT INTO MERCE(id_merce, tags) VALUES('2', 'BRETELLA FO-LC-LC-50/125 10M');
INSERT INTO MERCE(id_merce, tags) VALUES('3', 'BRETELLA UTP-CAT6 3M giallo');
INSERT INTO MERCE(id_merce, tags) VALUES('4', 'BRETELLA UTP-CAT6 3M blu');
INSERT INTO MERCE(id_merce, tags) VALUES('5', 'BRETELLA UTP-CAT5E 3M');
INSERT INTO MERCE(id_merce, tags) VALUES('6', 'BRETELLA FO-LC-LC-50/125 5M');
INSERT INTO MERCE(id_merce, tags) VALUES('7', 'SERVER FUJITSU RX600 PY RX600 S6 S26361-K1402-V400');
INSERT INTO MERCE(id_merce, tags) VALUES('8', 'APPARATI SWITCH KVM S4-0812 digital vm 1he S26361-K1393-V8 switch monitor tastiera rack');
INSERT INTO MERCE(id_merce, tags) VALUES('9', 'APPARATI MONITOR 17inch rack tft rc25 43cm S26361-K1387-V600 monitor rack');
INSERT INTO MERCE(id_merce, tags) VALUES('10', 'APPARATI ADAPTER USB-VGA KabelS26361-F4473-L230 console rack');
INSERT INTO MERCE(id_merce, tags) VALUES('11','APPARATI CHASSIS ENCLOSURE BLADE LCD HP BLC7000');
INSERT INTO MERCE(id_merce, tags) VALUES('12','SERVER BLADE HP BL460c 641016-B21HP Gen8 10Gb FLB CTO');
INSERT INTO MERCE(id_merce, tags) VALUES('13','APPARATI POSTEMOBILE RSS4000-HD-WEB STREAM-UPG 5150-32759-001 videoconferenza');
INSERT INTO MERCE(id_merce, tags) VALUES('14','BRETELLA UTP-CAT5E 2M');
INSERT INTO MERCE(id_merce, tags) VALUES('16','APPARATI DVDRW HP Mobile USB nLS DVDRW Drive A2U57AA');
INSERT INTO MERCE(id_merce, tags) VALUES('17','ATTREZZI SL8500 cassa');
INSERT INTO MERCE(id_merce, tags) VALUES('18','APPARATI SWITCH POSTEL BLADE EC-1700-B CONNECTRIX B SERIES CABINET');
INSERT INTO MERCE(id_merce, tags) VALUES('19','BRETELLA FO-LC-LC-50/125 30M');
INSERT INTO MERCE(id_merce, tags) VALUES('20','APPARATI STORAGE VMAXSB-SYS-TOPKIT vmax system bay');
INSERT INTO MERCE(id_merce, tags) VALUES('21','APPARATI STORAGE VMAX STORAGESB-DB-TOP-KIT vmax storage bay');
INSERT INTO MERCE(id_merce, tags) VALUES('22','APPARATI STORAGE EMC ATMOS POSTEL1 rack emc atmos 800kg');
INSERT INTO MERCE(id_merce, tags) VALUES('23','ATTREZZI STORAGE ORACLE SL8500 TAPE CLEARING 31840741 pulitori nastri');
INSERT INTO MERCE(id_merce, tags) VALUES('24','APPARATI MONITOR 65inch LED MD65CSMMD65C overlay protection glass touch');
INSERT INTO MERCE(id_merce, tags) VALUES('25','APPARATI PLUG IN MODULE CPU AMDSBB-PQ32BV4/ENcomputer tv cpu amd A8-3510M');
INSERT INTO MERCE(id_merce, tags) VALUES('26','APPARATI FIREWALL POSTEMOBILE CERT GX4004C-V2-1-Pproventia gx4004c-v2 ips 1u');
INSERT INTO MERCE(id_merce, tags) VALUES('27','APPARATI DISCHI 8TB STORAGE POSTEL Nodi raw 4_da_2TB tot_64TB raw');
INSERT INTO MERCE(id_merce, tags) VALUES('28','COMPONENTI LICENZASOFTWARE CENTRASTARCentrastar GOVERNANCE EDITION PARITY REPLICATION');
INSERT INTO MERCE(id_merce, tags) VALUES('29','APPARATI SWITCH CISCO WS-C2960S-48TS-Lswitch 10029295');
INSERT INTO MERCE(id_merce, tags) VALUES('30','APPARATI SWITCH POSTEMOBILE SCHEDE N7K-C7009-B2S2E-R');
INSERT INTO MERCE(id_merce, tags) VALUES('31','APPARATI SWITCH POSTEMOBILE SCHEDE ASR-9006-AC-V2 materiale telecomunicazioni 10035580');
INSERT INTO MERCE(id_merce, tags) VALUES('32','APPARATI CHECKPOINT POSTEMOBILE GATEWAY cpap-sg4800-ngfw-vs10-2 4800 NGFW VS appliance bundle');
INSERT INTO MERCE(id_merce, tags) VALUES('33','SERVER RMA');
INSERT INTO MERCE(id_merce, tags) VALUES('34','APPARATI KVM RMA');
INSERT INTO MERCE(id_merce, tags) VALUES('35','APPARATI MONITOR TFT FUJITSU RC-23');
INSERT INTO MERCE(id_merce, tags) VALUES('36','APPARATI SWITCH CISCOMDS 9513');
INSERT INTO MERCE(id_merce, tags) VALUES('37','APPARATI SWITCH CISCO NEXSUS POSTEMOBILE 2232P');
INSERT INTO MERCE(id_merce, tags) VALUES('38','APPARATI SWITCH CISCO POSTEMOBILE n5k-c5548up-fa materiale telecomunicazioni 10034661');
INSERT INTO MERCE(id_merce, tags) VALUES('39','APPARATI SWITCH CISCO POSTEMOBILE n2k-2232pf-10ge');
INSERT INTO MERCE(id_merce, tags) VALUES('41','BRETELLA FO-LC-LC-50/125 12M');
INSERT INTO MERCE(id_merce, tags) VALUES('42','ATTREZZI SPINE Spine industriali 32A 5poli');
INSERT INTO MERCE(id_merce, tags) VALUES('43','APPARATI STORAGE IBM DS8800 50.4TB IBM 2423.951 S/N_75AZM80 7drive 450GB 112 dischi 64GB cache 32porte FC SW backend Storage console sspc 2805-MC5');
INSERT INTO MERCE(id_merce, tags) VALUES('44','APPARATI SWITCH IBM SAN 32 C21M02IBM SAN 768B 2499-384 blade 32porte S/N_106562P-106563X-106564L-106564E-106564P-106563D');
INSERT INTO MERCE(id_merce, tags) VALUES('45','APPARATI SWITCH IBM SAN 48 C21M02IBM SAN 768B 2499-384 blade 48porte S/N_106564F-106563Z-106563R-106564D');
INSERT INTO MERCE(id_merce, tags) VALUES('46','BRETELLA FO-LC-LC-50/125 3M');
INSERT INTO MERCE(id_merce, tags) VALUES('47','BRETELLA FO-LC-LC-50/125 12,5M');
INSERT INTO MERCE(id_merce, tags) VALUES('48','BRETELLA FO-LC-LC-50/125 15M');
INSERT INTO MERCE(id_merce, tags) VALUES('49','BRETELLA FO-LC-LC-50/125 20M');
INSERT INTO MERCE(id_merce, tags) VALUES('50','BRETELLA FO-LC-SC-50/125 3M');
INSERT INTO MERCE(id_merce, tags) VALUES('51','BRETELLA FO-SC-SC-50/125 3M');
INSERT INTO MERCE(id_merce, tags) VALUES('52','BRETELLA FO-LC-LC-9/125 3M');
INSERT INTO MERCE(id_merce, tags) VALUES('53','BRETELLA FO-LC-SC-9/125 3M');
INSERT INTO MERCE(id_merce, tags) VALUES('54','BRETELLA UTP-CAT6 3M');
INSERT INTO MERCE(id_merce, tags) VALUES('55','VARI CAPPUCCI COLOUR CODING PATCH C6 GIALLO');
INSERT INTO MERCE(id_merce, tags) VALUES('56','VARI CAPPUCCI COLOUR CODING PATCH C6 BLUE');
INSERT INTO MERCE(id_merce, tags) VALUES('57','BRETELLA UTP-CAT5E 5M');
INSERT INTO MERCE(id_merce, tags) VALUES('58','VARI HP FLASH USB608447-B21HP 2GB USB FLASH MEDIA DRIVE KEY KIT');
INSERT INTO MERCE(id_merce, tags) VALUES('59','BRETELLA UTP-CAT6 2M');
INSERT INTO MERCE(id_merce, tags) VALUES('60','APPARATI TELEFONO VOIP');
INSERT INTO MERCE(id_merce, tags) VALUES('61','VARI pt_number');
INSERT INTO MERCE(id_merce, tags) VALUES('62','APPARATI STORAGE IBM DS8800 57.6TB');
INSERT INTO MERCE(id_merce, tags) VALUES('63','BRETELLA FO-LC-LC-50/125 50M');
INSERT INTO MERCE(id_merce, tags) VALUES('64','APPARATI VBLOCK VB320-5700V06WT714001-01-02-03');
INSERT INTO MERCE(id_merce, tags) VALUES('65','VARI PASSACAVI');
INSERT INTO MERCE(id_merce, tags) VALUES('66','COMPONENTI ADATTATORE PER FIBRESFP-10G-SR');
INSERT INTO MERCE(id_merce, tags) VALUES('67','COMPONENTI ADATTATORE CAVI RAMECSY:GLC-T');
INSERT INTO MERCE(id_merce, tags) VALUES('68','APPARATI SWITCH 48-PORTCATALYST 4948E OPT SW');
INSERT INTO MERCE(id_merce, tags) VALUES('69','BRETELLA FO-LC-LC-50/125 26M');
INSERT INTO MERCE(id_merce, tags) VALUES('70','BRETELLA FO-LC-LC-50/125 27M');
INSERT INTO MERCE(id_merce, tags) VALUES('71','BRETELLA FO-LC-LC-50/125 35M');
INSERT INTO MERCE(id_merce, tags) VALUES('72','SERVER HP DL380PGEN8653200-B21');
INSERT INTO MERCE(id_merce, tags) VALUES('73','SERVER HP DL380PGEN8665653-B21');
INSERT INTO MERCE(id_merce, tags) VALUES('74','SERVER HP DL360');
INSERT INTO MERCE(id_merce, tags) VALUES('75','APPARATI DISTRIBUTIONPOWER');
INSERT INTO MERCE(id_merce, tags) VALUES('76','BRETELLA FO-LC-LC-50/125 25M');
INSERT INTO MERCE(id_merce, tags) VALUES('77','BRETELLA FO-LC-LC-50/125 40M');
INSERT INTO MERCE(id_merce, tags) VALUES('78','Pannelli Plastica 1UR Plexiglass');
INSERT INTO MERCE(id_merce, tags) VALUES('79','Pannelli Plastica 2UR Plexiglass'); 
INSERT INTO MERCE(id_merce, tags) VALUES('80','Pannelli Plastica 3UR Plexiglass');
INSERT INTO MERCE(id_merce, tags) VALUES('81','Pannelli Plastica 5UR Plexiglass');
INSERT INTO MERCE(id_merce, tags) VALUES('82','Pannelli Plastica 10UR Plexiglass');
INSERT INTO MERCE(id_merce, tags) VALUES('83','Minuteria Viti dadi gabbia Scatola');
INSERT INTO MERCE(id_merce, tags) VALUES('84','APPARATI SWITCH POSTEMOBILE CISCOCSY N2K-C2232TF-E');
INSERT INTO MERCE(id_merce, tags) VALUES('85','APPARATI FIREWALL POSTEMOBILE CISCO ASA CSYMP ASA5525VPN-EM750K9');

