USE magazzino;

-- etichette
TRUNCATE TABLE etichette;

-- etichette tags sel 1
CALL input_etichette('1','ATTREZZI');
CALL input_etichette('1','BRETELLA');
CALL input_etichette('1','APPARATI');
CALL input_etichette('1','COMPONENTI');
CALL input_etichette('1','Minuteria');
CALL input_etichette('1','Pannelli');
CALL input_etichette('1','SERVER');
CALL input_etichette('1','VARI');
CALL input_etichette('1','Viteria');
CALL input_etichette('1','ADAPTER');
CALL input_etichette('1','BLADE');
CALL input_etichette('1','CHASSIS');
CALL input_etichette('1','CHECKPOINT');
CALL input_etichette('1','DISCHI');
CALL input_etichette('1','DISTRIBUTIONPOWER');
CALL input_etichette('1','DVDRW');
CALL input_etichette('1','FIREWALL');
CALL input_etichette('1','FO-LC-LC-50/125');
CALL input_etichette('1','FO-LC-LC-9/125');
CALL input_etichette('1','FO-LC-SC-50/125');
CALL input_etichette('1','FO-LC-SC-9/125');
CALL input_etichette('1','FO-SC-SC-50/125');
CALL input_etichette('1','HPDL360');
CALL input_etichette('1','HPDL380PGEN8');
CALL input_etichette('1','KVM');
CALL input_etichette('1','LICENZASOFTWARE');
CALL input_etichette('1','MONITOR');
CALL input_etichette('1','Plastica');
CALL input_etichette('1','SPINE');
CALL input_etichette('1','STORAGE');
CALL input_etichette('1','SWITCH');
CALL input_etichette('1','UTP');
CALL input_etichette('1','CAT5E');
CALL input_etichette('1','CAT6');
CALL input_etichette('1','Vitiedadigabbia');
CALL input_etichette('1','10M');
CALL input_etichette('1','10UR');
CALL input_etichette('1','12,5M');
CALL input_etichette('1','12M');
CALL input_etichette('1','15M');
CALL input_etichette('1','17inch');
CALL input_etichette('1','1UR');
CALL input_etichette('1','20M');
CALL input_etichette('1','25M');
CALL input_etichette('1','26M');
CALL input_etichette('1','27M');
CALL input_etichette('1','2M');
CALL input_etichette('1','2UR');
CALL input_etichette('1','30M');
CALL input_etichette('1','35M');
CALL input_etichette('1','3M');
CALL input_etichette('1','3UR');
CALL input_etichette('1','50M');
CALL input_etichette('1','5M');
CALL input_etichette('1','5UR');
CALL input_etichette('1','65inch');
CALL input_etichette('1','8TB');
CALL input_etichette('1','Pacchi');
CALL input_etichette('1','Scatola');
CALL input_etichette('1','USB');
CALL input_etichette('1','VGA');
CALL input_etichette('1','3m-Kabel');
CALL input_etichette('1','48-PORT');
CALL input_etichette('1','ADATTATORE');
CALL input_etichette('1','CAVI');
CALL input_etichette('1','RAME');
CALL input_etichette('1','FIBRA');
CALL input_etichette('1','blu');
CALL input_etichette('1','CENTRASTAR');
CALL input_etichette('1','CISCO');
CALL input_etichette('1','NEXSUS');
CALL input_etichette('1','COLOUR');
CALL input_etichette('1','CODING');
CALL input_etichette('1','PATCH');
CALL input_etichette('1','C6');
CALL input_etichette('1','BLUE');
CALL input_etichette('1','GIALLO');
CALL input_etichette('1','EMC');
CALL input_etichette('1','ATMOS');
CALL input_etichette('1','POSTEL');
CALL input_etichette('1','ENCLOSURE');
CALL input_etichette('1','LCD');
CALL input_etichette('1','FUJITSU');
CALL input_etichette('1','RX600');
CALL input_etichette('1','giallo');
CALL input_etichette('1','HP');
CALL input_etichette('1','FLASH');
CALL input_etichette('1','IBM');
CALL input_etichette('1','3850-X5');
CALL input_etichette('1','DS8800');
CALL input_etichette('1','50.4TB');
CALL input_etichette('1','57.6TB');
CALL input_etichette('1','SAN');
CALL input_etichette('1','48');
CALL input_etichette('1','LED');
CALL input_etichette('1','MD65C');
CALL input_etichette('1','ORACLE');
CALL input_etichette('1','SL8500');
CALL input_etichette('1','TAPE');
CALL input_etichette('1','CLEARING');
CALL input_etichette('1','PASSACAVI');
CALL input_etichette('1','Plexiglass');
CALL input_etichette('1','PLUGIN');
CALL input_etichette('1','MODULE');
CALL input_etichette('1','CPU');
CALL input_etichette('1','AMD');
CALL input_etichette('1','POSTEL');
CALL input_etichette('1','POSTEMOBILE');
CALL input_etichette('1','CERT');
CALL input_etichette('1','ASA');
CALL input_etichette('1','GATEWAY');
CALL input_etichette('1','SCHEDE');
CALL input_etichette('1','ptnumber');
CALL input_etichette('1','RX600');
CALL input_etichette('1','RACK');
CALL input_etichette('1','TFT');
CALL input_etichette('1','RC25');
CALL input_etichette('1','43cm');
CALL input_etichette('1','RMA');
CALL input_etichette('1','S4-0812');
CALL input_etichette('1','digital');
CALL input_etichette('1','vm_1he');
CALL input_etichette('1','SL8500');
CALL input_etichette('1','TELEFONO');
CALL input_etichette('1','VOIP');
CALL input_etichette('1','VBLOCK');
CALL input_etichette('1','VMAX');
CALL input_etichette('1','STORAGE');

-- etichette posizioni sel 2
CALL input_etichette('2','A1L02');
CALL input_etichette('2','A1L05');
CALL input_etichette('2','A1L11');
CALL input_etichette('2','A1L12');
CALL input_etichette('2','A1L13');
CALL input_etichette('2','A2L01');
CALL input_etichette('2','A2L02');
CALL input_etichette('2','A2L03');
CALL input_etichette('2','A2L04');
CALL input_etichette('2','A2L05');
CALL input_etichette('2','A2L09');
CALL input_etichette('2','A2L10');
CALL input_etichette('2','A2L13');
CALL input_etichette('2','A2L14');
CALL input_etichette('2','B1L02');
CALL input_etichette('2','B1L03');
CALL input_etichette('2','B1L04');
CALL input_etichette('2','B1L11');
CALL input_etichette('2','B1L13');
CALL input_etichette('2','B2-L4');
CALL input_etichette('2','B2-L5');
CALL input_etichette('2','P01');
CALL input_etichette('2','P05');
CALL input_etichette('2','P06');
CALL input_etichette('2','P10');
CALL input_etichette('2','P17');
CALL input_etichette('2','Z1L08');

-- etichette destinazioni sel 3
CALL input_etichette('3','SALA1');
CALL input_etichette('3','temp');
CALL input_etichette('3','UFFICIO1');
CALL input_etichette('3','SALA1-ISOLA5');
CALL input_etichette('3','SALA1-ISOLA6');
CALL input_etichette('3','SALA1-ISOLASTORAGE');
CALL input_etichette('3','SALA1ISOLA2');
CALL input_etichette('3','SALA2');
CALL input_etichette('3','TLCA');
CALL input_etichette('3','TLCB');
CALL input_etichette('3','UFFICI');
CALL input_etichette('3','INGRESSO');

-- etichette tipi di documenti sel 4
CALL input_etichette('4','BDC');
CALL input_etichette('4','DDT');
CALL input_etichette('4','eMail');
CALL input_etichette('4','Lettera_di_vettura');
CALL input_etichette('4','MDS');
CALL input_etichette('4','ODA');
CALL input_etichette('4','Verbale_di_consegna_ed_installazione');
CALL input_etichette('4','CarrierB');

-- etichette registro sel 5
CALL input_etichette('5','BRT SPA');
CALL input_etichette('5','CAMI SOLUTION');
CALL input_etichette('5','Carugati Luigi S.r.l.');
CALL input_etichette('5','CEVA LOGISTIC ITALIA SRL');
CALL input_etichette('5','Computer Gross Italia S.p.A.');
CALL input_etichette('5','Converge S.p.A.');
CALL input_etichette('5','D&T Delli TecnoTrans S.r.l.');
CALL input_etichette('5','DGS S.p.A.');
CALL input_etichette('5','DHL Express');
CALL input_etichette('5','EMC Computer Systems Italia S.p.a.');
CALL input_etichette('5','Ericsson Telecomunicazioni S.p.A');
CALL input_etichette('5','EXECUTIVE');
CALL input_etichette('5','Fimm S.R.L.');
CALL input_etichette('5','Fujitsu Technology Solutions S.r.l.');
CALL input_etichette('5','G.F.O. Europe S.r.l.');
CALL input_etichette('5','Gebrueder Weiss GmbH Transport und Logistik');
CALL input_etichette('5','Hewlett Packard International Sarl');
CALL input_etichette('5','Hewlett Packard Italiana S.p.A.');
CALL input_etichette('5','HMS IT S.p.A.');
CALL input_etichette('5','ICT Logistica S.p.A.');
CALL input_etichette('5','IRCE SPA');
CALL input_etichette('5','Italia Logistica S.R.L.');
CALL input_etichette('5','Italtel S.p.A.');
CALL input_etichette('5','Laziale Distribuzione');
CALL input_etichette('5','LUPPRIANS');
CALL input_etichette('5','Mauden S.p.a.');
CALL input_etichette('5','MITSafetrans S.r.l.');
CALL input_etichette('5','NBI S.R.L.');
CALL input_etichette('5','Nouwens Transport Breda');
CALL input_etichette('5','Oracle Corporation');
CALL input_etichette('5','Polo Immobiliare');
CALL input_etichette('5','Polycom');
CALL input_etichette('5','Poste Italiane S.p.a.');
CALL input_etichette('5','Poste Italiane S.p.a. Immobiliare');
CALL input_etichette('5','Poste Italiane S.p.a. ROMA');
CALL input_etichette('5','PosteMobile S.p.a.');
CALL input_etichette('5','R&M');
CALL input_etichette('5','Rhenus Logistics');
CALL input_etichette('5','RTI INFORDATA S.p.a.');
CALL input_etichette('5','Safe Watcher S.r.l.');
CALL input_etichette('5','SDA Express Courier');
CALL input_etichette('5','Sioli & Fontana S.r.l.');
CALL input_etichette('5','Tecnotrans S.r.l.');
CALL input_etichette('5','Telecom Italia');
CALL input_etichette('5','TRADIS di Giuseppe Pullella');

